name: Build

#on:
#  create:
#    tags:
#      - '*'
on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install graphicsmagick
        run: |
          sudo apt-get update
          sudo apt-get install -y graphicsmagick
      - name: Install Start Run
        run: |
          npm install
          npm start
          npm run package
          
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install graphicsmagick
        run: |
          brew install graphicsmagick
  
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - name: Install GraphicsMagick
        run: |
          choco install graphicsmagick
      - name: Add GraphicsMagick path
        run: |
          $env:Path += ";C:\Program Files\GraphicsMagick-1.3.36-Q16"
      - name: Verify
        run: |
          gm version
